### ISSUE TITLE
Will you share a contribution guideline?

### ISSUE THREAD

**Issue by MelihDarcanxyz** [TokTok/btox#32]
I'm aware of Tox protocol since last year. After meeting Tox I was fascinated and wanted to build an app for it which is easy to use and has a nice user interface. I was planning on that for a long time and it's semester break in my country so I thought why not make it real?

For the past few weeks I was doing research and learning some front-end web development just for this project. I was planning to do Electron + React but then thought that Flutter was a good option too. I found out about Dart FFI and realized that it could come in handy very much. Finally I found this repository (remembered actually) and thought to myself "Why not contribute to already existing project rather than inventing the wheel two times."

So here I am, I couldn't find a way to contact to TokTok and that's why you're reading this. Sorry for that. I'm open to anything just help (and let) me to contribute. I'm very dedicated about this project.

**Comment by zoff99** [comment]
Hi @MelihDarcanxyz 
thank you for your interest.
can you please join us on IRC [#toktok@libera.chat](https://web.libera.chat/#toktok)
